### ISSUE TITLE
SQLite possible?

### ISSUE THREAD

**Issue by quaasi** [MatKrl/twitterlike#1]
Hi @MatKrl ,

would it be possible to change the database adapter to sqlite3? It would be much easier for me to setup as I have no mysql installation. Or does your app depend on some specific mysql features.

Thanks

**Comment by MatKrl** [comment]
Yes, sure. It should be quite easy. I will try tomorrow and let you know.

**Comment by MatKrl** [comment]
Done. App is using sqlite3 now.
